 // ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.IO;
using System.Collections;
using System.Collections.Generic;
using System;
using AOT;
using System.Runtime.InteropServices;

public class GLinkiOS : MonoBehaviour, IGLink
{
	#if UNITY_IPHONE
	[DllImport("__Internal")]
	public static extern void _InitGLink(string clientId, string clientSecret, string loungeId);

	[DllImport("__Internal")]
	public static extern string _GetSdkVersion();

	[DllImport("__Internal")]
	public static extern string _GetCountryCode();

	[DllImport("__Internal")]
	public static extern void _SetCanWriteFeedByScreenshot(bool enabled);

	[DllImport("__Internal")]
	public static extern void _SetGameId(string gameId);
	
	[DllImport("__Internal")]
	public static extern void _ExecuteHomeBanner();

	[DllImport("__Internal")]
	public static extern void _ExecuteSorryBanner();

	[DllImport("__Internal")]
	public static extern void _ExecuteBoard(int boardId);

	[DllImport("__Internal")]
	public static extern void _ExecuteFeed(long feedId, bool isTempFeedId);

	[DllImport("__Internal")]
	public static extern void _ExecuteFeedWriting(int boardId, string title, string text, string imageFilePath);

	[DllImport("__Internal")]
	public static extern void _TerminateSdk();

	[DllImport("__Internal")]
	public static extern void _NaverLogout();
	
	[DllImport("__Internal")]
	private static extern void _SetSDKDidLoadDelegate(NGSDKDidLoadDelegate callback);
	
	[DllImport("__Internal")]
	private static extern void _SetSDKDidUnloadDelegate(NGSDKDidUnloadDelegate callback);

	[DllImport("__Internal")]
	private static extern void _SetSDKDidReceiveInGameMenuCodeDelegate(NGSDKDidReceiveInGameMenuCodeDelegate callback);
	#endif
	
	#if UNITY_IPHONE
	delegate void NGSDKDidLoadDelegate();
	[MonoPInvokeCallback(typeof(NGSDKDidLoadDelegate))]
	public static void _NGSDKDidLoadCallback () {
		GLinkDelegate._callSdkOpened();
	}
	
	delegate void NGSDKDidUnloadDelegate();
	[MonoPInvokeCallback(typeof(NGSDKDidUnloadDelegate))]
	public static void _NGSDKDidUnloadCallback () {
		GLinkDelegate._callSdkClosed();
	}

	delegate void NGSDKDidReceiveInGameMenuCodeDelegate(string inGameMenuCode);
	[MonoPInvokeCallback(typeof(NGSDKDidReceiveInGameMenuCodeDelegate))]
	public static void _NGSDKDidReceiveInGameMenuCodeDelegate(string inGameMenuCode) {
		GLinkDelegate._callSdkInGameMenuCode(inGameMenuCode);
	}
	#endif
	
	public GLinkiOS() {
		#if UNITY_IPHONE		
		// Set callbacks.
		_SetSDKDidLoadDelegate(_NGSDKDidLoadCallback);
		_SetSDKDidUnloadDelegate(_NGSDKDidUnloadCallback);
		_SetSDKDidReceiveInGameMenuCodeDelegate(_NGSDKDidReceiveInGameMenuCodeDelegate);
		#endif
	}

	public void init(string loungeId, string clientId, string clientSecret) {
        #if UNITY_IPHONE
        _InitGLink(clientId, clientSecret, loungeId);   
        #endif
    }

    public string getSdkVersion() {
		#if UNITY_IPHONE
		return _GetSdkVersion();
	    #else
	    return "";
		#endif
    }

    public string getCountryCode() {
		#if UNITY_IPHONE
		return _GetCountryCode();
	    #else
	    return "";
		#endif
    }

    public void setCanWriteFeedByScreenshot(bool enabled) {
    	#if UNITY_IPHONE
		_SetCanWriteFeedByScreenshot(enabled);
	    #endif
    }

    public void setGameId(string gameId) {
    	#if UNITY_IPHONE
		_SetGameId(gameId);
	    #endif
    }
	
	public void executeHomeBanner() {
		#if UNITY_IPHONE 
		_ExecuteHomeBanner();
		#endif
	}

	public void executeSorryBanner() {
		#if UNITY_IPHONE 
		_ExecuteSorryBanner();
		#endif
	}
    
    public void executeBoard(int boardId) {
		#if UNITY_IPHONE
	    _ExecuteBoard(boardId);
		#endif
    }

    public void executeFeed(long feedId, bool isTempFeedId) {
		#if UNITY_IPHONE
	    _ExecuteFeed(feedId, isTempFeedId);
		#endif
    }

    public void executeFeedWriting(int boardId, string title, string text, string imageFilePath) {
		#if UNITY_IPHONE
	    _ExecuteFeedWriting(boardId, title, text, imageFilePath);
		#endif
    }

    public void terminateSdk() {
		#if UNITY_IPHONE
	    _TerminateSdk();
		#endif
    }
    
    public void naverLogout() {
		#if UNITY_IPHONE
	    _NaverLogout();
		#endif	
    }
}