// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Runtime.InteropServices;

public class GLinkAndroid : IGLink {

	#if UNITY_ANDROID
	AndroidJavaClass glinkClass = null;
	AndroidJavaObject currentActivity = null;
	
	class OnSdkLoadListener : AndroidJavaProxy {
		public OnSdkLoadListener () : base("com.navercorp.nng.android.sdk.NNGCallbackListener") { /* empty. */ }

		public void onSdkDidLoaded() {
		    GLinkDelegate._callSdkOpened();
		}
        public void onSdkDidUnloaded(){
            GLinkDelegate._callSdkClosed();
        }
        public void onExecuteMenuEvent(string moveTo) {
            GLinkDelegate._callSdkScheme(moveTo);
        }

	}


	#endif

	public GLinkAndroid () {
		#if UNITY_ANDROID
		currentActivity = new AndroidJavaClass ("com.unity3d.player.UnityPlayer").GetStatic<AndroidJavaObject> ("currentActivity");
		glinkClass = new AndroidJavaClass ("com.navercorp.nng.android.sdk.NNGLink");
		
        glinkClass.CallStatic ("setSdkLoadListener", new OnSdkLoadListener ());

 		#endif
	}
	
	public string getSdkVersion()
	{
#if UNITY_ANDROID
		return glinkClass.CallStatic<string>("getSdkVersionName");
#endif
		return null;
	}

	public void executeHomeBanner() {
		#if UNITY_ANDROID
		glinkClass.CallStatic("startHome",currentActivity);
		// glinkClass.CallStatic("startWebView",currentActivity,"url");
		#endif
	}
	
	public void executeSorryBanner() {
		#if UNITY_ANDROID
		glinkClass.CallStatic("startSorry",currentActivity);
		// glinkClass.CallStatic("startWebView",currentActivity,"url");
		#endif
	}

	public void executeArticleList(int menuId)
	{
#if UNITY_ANDROID
        glinkClass.CallStatic("startArticleList",currentActivity,menuId);
#endif
    }

	public void executeArticleByFeedId(long feedId)
	{
#if UNITY_ANDROID
		glinkClass.CallStatic("startArticle",currentActivity,feedId);
#endif
	}

	public void init(string loungeId, string clientId, string clientSecret)
    {
        #if UNITY_ANDROID
	    glinkClass.CallStatic("initModule",currentActivity,loungeId,clientId,clientSecret);
        #endif
    }

	public void unloadSdk()
	{
#if UNITY_ANDROID
		glinkClass.CallStatic("unloadSdk");
#endif
	}

}
