// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Runtime.InteropServices;

public class GLinkAndroid : IGLink {

	#if UNITY_ANDROID
	AndroidJavaClass glinkClass = null;
	AndroidJavaObject currentActivity = null;

	class OnClickAppSchemeBannerListener : AndroidJavaProxy {
		public OnClickAppSchemeBannerListener () : base("com.naver.glink.android.sdk.Glink$OnClickAppSchemeBannerListener") { /* empty. */ }

		void onClickAppSchemeBanner (string appScheme) {
			showToast ("tapped:" + appScheme);
		}
	}

	class OnSdkStartedListener : AndroidJavaProxy {
		public OnSdkStartedListener () : base("com.naver.glink.android.sdk.Glink$OnSdkStartedListener") { /* empty. */ }

		void onSdkStarted () {
			showToast ("sdk start.");
		}
	}

	class OnSdkStoppedListener : AndroidJavaProxy {
		public OnSdkStoppedListener () : base("com.naver.glink.android.sdk.Glink$OnSdkStoppedListener") { /* empty. */ }

		void onSdkStopped () {
			showToast ("sdk stop.");
		}
	}


	static void showToast(string message) {
        //var activity = new AndroidJavaClass("com.unity3d.player.UnityPlayer").GetStatic<AndroidJavaObject>("currentActivity");
        //activity.Call("runOnUiThread", new AndroidJavaRunnable(() =>
        //{
        //    AndroidJavaObject toast = new AndroidJavaClass("android.widget.Toast").CallStatic<AndroidJavaObject>("makeText", activity, message, 1);
        //    toast.Call("show");
        //}));
    }
	#endif

	public GLinkAndroid () {
		#if UNITY_ANDROID
		currentActivity = new AndroidJavaClass ("com.unity3d.player.UnityPlayer").GetStatic<AndroidJavaObject> ("currentActivity");
		glinkClass = new AndroidJavaClass ("com.navercorp.nng.android.sdk.NNGLink");

        // Move to /Assets/NCSDK/Sample/SampleBehaviour.cs 
        //glinkClass.CallStatic("init", currentActivity, GLinkConfig.NaverLoginClientId, GLinkConfig.NaverLoginClientSecret, GLinkConfig.LoungeId);

        // 앱스킴 listener 사용 하려면 아래 주석을 풀어 주세요.
        // glinkClass.CallStatic ("setOnClickAppSchemeBannerListener", new OnClickAppSchemeBannerListener ());

        // sdk start listener 사용 하려면 아래 주석을 풀어 주세요.
        // glinkClass.CallStatic ("setOnSdkStartedListener", new OnSdkStartedListener ());

        // sdk stop listener 사용 하려면 아래 주석을 풀어 주세요.
        // glinkClass.CallStatic ("setOnSdkStoppedListener", new OnSdkStoppedListener ());

 		#endif
	}

	public void executeHomeBanner() {
		#if UNITY_ANDROID
		glinkClass.CallStatic("startHome",currentActivity);
		// glinkClass.CallStatic("startWebView",currentActivity,"url");
		#endif
	}
	
	public void executeSorryBanner() {
		#if UNITY_ANDROID
		glinkClass.CallStatic("startSorry",currentActivity);
		// glinkClass.CallStatic("startWebView",currentActivity,"url");
		#endif
	}

    public void init(string loungeId, string clientId, string clientSecret)
    {
        #if UNITY_ANDROID
	    glinkClass.CallStatic("initModule",currentActivity,loungeId,clientId,clientSecret);
        #endif
    }
}
