 // ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.IO;
using System.Collections;
using System.Collections.Generic;
using System;
using AOT;
using System.Runtime.InteropServices;

public class GLinkiOS : MonoBehaviour, IGLink
{
	#if UNITY_IPHONE
	[DllImport("__Internal")]
	public static extern void _InitGLink(string consumerKey, string consumerSecret, string loungeId);
	
	[DllImport("__Internal")]
	public static extern void _ExecuteHomeBanner();

	[DllImport("__Internal")]
	public static extern void _ExecuteSorryBanner();
	
	[DllImport("__Internal")]
	private static extern void _SetSDKDidLoadDelegate(NGSDKDidLoadDelegate callback);
	
	[DllImport("__Internal")]
	private static extern void _SetSDKDidUnloadDelegate(NGSDKDidUnloadDelegate callback);
	#endif
	
	#if UNITY_IPHONE
	delegate void NGSDKDidLoadDelegate();
	[MonoPInvokeCallback(typeof(NGSDKDidLoadDelegate))]
	public static void _NGSDKDidLoadCallback () {
		// Write codes performed when the NNGSDK is loaded.
	}
	
	delegate void NGSDKDidUnloadDelegate();
	[MonoPInvokeCallback(typeof(NGSDKDidUnloadDelegate))]
	public static void _NGSDKDidUnloadCallback () {
		// Write codes performed when the NNGSDK is unloaded.
	}
	#endif
	
	public GLinkiOS() {
		#if UNITY_IPHONE
		_InitGLink(GLinkConfig.NaverLoginClientId, GLinkConfig.NaverLoginClientSecret, GLinkConfig.LoungeId);
		
		// Set callbacks.
		_SetSDKDidLoadDelegate(_NGSDKDidLoadCallback);
		_SetSDKDidUnloadDelegate(_NGSDKDidUnloadCallback);
		#endif
	}
	
	public void executeHomeBanner() {
		#if UNITY_IPHONE 
		_ExecuteHomeBanner();
		#endif
	}

	public void executeSorryBanner() {
		#if UNITY_IPHONE 
		_ExecuteSorryBanner();
		#endif
	}

    public void init(string loungeId, string clientId, string clientSecret)
    {
        #if UNITY_IPHONE
        _InitGLink(clientId, clientSecret, loungeId);   
        #endif
    }

}