// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

public interface IGLink
{
	void init(string loungeId, string clientId, string clientSecret);
	void terminateSdk();
	
	void executeHomeBanner();
	void executeSorryBanner();

	void executeBoard(int boardId);
	void executeFeed(long feedId, bool isTempFeedId);
	
	string getSdkVersion();
	string getCountryCode();
	

}
