// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;

public class GLinkAndroid : IGLink {

	#if UNITY_ANDROID
	AndroidJavaClass glinkClass = null;
	AndroidJavaObject currentActivity = null;
	
	class OnSdkLoadListener : AndroidJavaProxy {
		public OnSdkLoadListener () : base("com.navercorp.nng.android.sdk.NNGCallbackListener") { /* empty. */ }

		public void onSdkDidLoaded() {
		    GLinkDelegate._callSdkOpened();
		}
        public void onSdkDidUnloaded(){
            GLinkDelegate._callSdkClosed();
        }
        public void onCallInGameMenuCode(string moveTo) {
            GLinkDelegate._callSdkInGameMenuCode(moveTo);
        }

	}


	#endif

	public GLinkAndroid () {
		#if UNITY_ANDROID
		currentActivity = new AndroidJavaClass ("com.unity3d.player.UnityPlayer").GetStatic<AndroidJavaObject> ("currentActivity");
		glinkClass = new AndroidJavaClass ("com.navercorp.nng.android.sdk.NNGLink");
		
        glinkClass.CallStatic ("setSdkLoadListener", new OnSdkLoadListener ());

 		#endif
	}
    public string getSdkVersion()
    {
#if UNITY_ANDROID
        return glinkClass.CallStatic<string>("getSdkVersionName");
#endif
        return null;
    }

	public string getCountryCode()
	{
#if UNITY_ANDROID
		return glinkClass.CallStatic<string>("getCountryCode",currentActivity);
#endif
		return null;
	}

	public void executeHomeBanner() {
		#if UNITY_ANDROID
		glinkClass.CallStatic("startHome",currentActivity);
#endif
	}
	
	public void executeSorryBanner() {
		#if UNITY_ANDROID
		glinkClass.CallStatic("startSorry",currentActivity);
#endif
	}

	public void executeBoard(int boardId)
	{
#if UNITY_ANDROID
        glinkClass.CallStatic("startBoard",currentActivity,boardId);
#endif
    }

	public void executeFeed(long feedId, bool isTempFeedId)
	{
#if UNITY_ANDROID
		glinkClass.CallStatic("startFeed",currentActivity,feedId,isTempFeedId);
#endif
	}

	public void executeFeedWriting(int boardId, string title, string text, string imageFilePath)
	{
#if UNITY_ANDROID
		glinkClass.CallStatic("writeFeed",currentActivity,boardId,title,text,imageFilePath);
#endif
	}

	public void setCanWriteFeedByScreenshot(bool enabled)
	{
#if UNITY_ANDROID
		glinkClass.CallStatic("enableScreenShotDetector",enabled);
#endif
	}

	public void setGameId(string gameId)
	{
#if UNITY_ANDROID
		glinkClass.CallStatic("putGameId",currentActivity,gameId);
#endif
	}

	public void init(string loungeId, string clientId, string clientSecret)
    {
        #if UNITY_ANDROID
	    glinkClass.CallStatic("initModule",currentActivity,loungeId,clientId,clientSecret);
        #endif
    }

	public void terminateSdk()
	{
#if UNITY_ANDROID
		glinkClass.CallStatic("finishSdk");
#endif
	}

}
